dockers:
  -
    goos: linux
    goarch: amd64
    image_templates:
      - "dingggu/cloudflare-access-controller:{{ .Tag }}"
      - "dingggu/cloudflare-access-controller:v{{ .Major }}"
      - "dingggu/cloudflare-access-controller:v{{ .Major }}.{{ .Minor }}"
      - "dingggu/cloudflare-access-controller:latest"